name = "CuisineBuilds-Expanded"
author = "Fyre520"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93d8680af41620fea0b762fa3aac69c4f9c87d5bd9f3e1c0a63f602a28678b7f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
